version: '2.4'
services:
  matlab:
    build: # only necessary if rebuilding image
      context: ..
      dockerfile: Dockerfile
      args:
        - MATLAB_VERSION
        - MATLAB_FILE_KEY
        - PY_VERSION
        - MATLAB_INSTALLED_ROOT
    #image: raphaelguzman/matlab:${MATLAB_VERSION}-${MATLAB_IMAGE_TYPE}
    image: drewyangdev/workflow_array_ephys:${MATLAB_VERSION}-${MATLAB_IMAGE_TYPE}
    environment:
      - DISPLAY # only necessary for GUI image
      - MATLAB_LICENSE # Must specify MATLAB_LICENSE variable or license file volume mount
      - MATLAB_USER
      - JUPYTER_PASSWORD=matlab # only necessary for GUI image
      - DJ_HOST
      - DJ_USER
      - DJ_PASS
      - DATABASE_PREFIX
      - EPHYS_ROOT_DATA_DIR=/home/${MATLAB_USER}/workflow_root_data
      - EPHYS_PROCESSED_DATA_DIR=/home/${MATLAB_USER}/workflow_processed_data
      - ecephys_directory
      - kilosort_repository
      - npy_matlab_repository
      - catGTPath
      - tPrime_path
      - cWaves_path
      - kilosort_output_tmp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    #user: ${MATLAB_UID}:${MATLAB_GID}
    volumes:
      #- /tmp/.X11-unix:/tmp/.X11-unix:rw # only necessary for GUI image
      # - ./licenses/${MATLAB_VERSION}_joseph_license.lic:/home/muser/license_${MATLAB_VERSION}.lic:ro # Must specify MATLAB_LICENSE variable or license file volume mount
      - /home/ubuntu/neuropixel/matlab-docker/matlab/licenses/${MATLAB_VERSION}_joseph_license.lic:/home/muser/.MATLAB/licenses/license_${MATLAB_VERSION}.lic:ro # Must specify MATLAB_LICENSE variable or license file volume mount
      - /home/ubuntu/neuropixel/data_for_ecephys:/home/muser/neuropixel/data_for_ecephys
      - ${ROOT_DATA_DIR}:/home/${MATLAB_USER}/workflow_root_data
      - ${PROCESSED_DATA_DIR}:/home/${MATLAB_USER}/workflow_processed_data
      - ./apt_requirements.txt:/tmp/apt_requirements.txt
    mac_address: $MATLAB_HOSTID
    scale: ${WORKER_COUNT:-1}
    command:
      - /bin/bash
      - -c
      - |
        cd /home/muser/neuropixel/Kilosort-3.0/CUDA && matlab -r "mexGPUall;quit" &&
        cd /home/muser/neuropixel/Kilosort-2.5/CUDA && matlab -r "mexGPUall;quit" &&
        cd /home/muser/neuropixel/sciops-demo-workflow-1 && run_workflow spike_sorting_worker &
        tail -f /dev/null
